FROM node:8.11.1-alpine
RUN apk add --update bash && rm -rf /var/cache/apk/*

# TIP: Always run npm install before copying any source files to your image
# RUN npm install --only=production

EXPOSE 3000
